#pragma once

/**
 * @class ConfigBuilder
 * @brief Constructs the final, strongly-typed configuration from a generic parse tree.
 *
 * This class takes the Intermediate Representation (IR) generated by the Parser,
 * validates the semantics of the directives (e.g., checks for valid port numbers),
 * and populates the final ServerConfig and LocationBlock objects. It bridges the
 * gap between syntax and a usable configuration.
 */
class ConfigBuilder {};
