name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code (including submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Cache build objects
        id: cache-obj
        uses: actions/cache@v4
        with:
          path: obj
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cpp', '**/*.hpp', 'Makefile', 'mk/*.mk') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cppcheck

      - name: Run static analysis (cppcheck)
        run: make check
        
      - name: Build the project
        run: make all

      - name: Run tests
        run: make test
